language: ruby
cache: bundler
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- jruby-19mode
- rbx
env:
  global:
  - secure: krDD3n+Fu7Ia3Wpm0/t1akFHNHmLVzk7efTa6AmGKmWkZltZTGNNPXnhIQAG+e4eYhgocT/Ia42Xx/7gMxRjKA4/N4FYhb8rGSj32h9NyXrdHFNjceUg7i8+G7BJvEtyda5PTDgrakDwsAIgCtvHw0Px2FjFV0J2wwKqEjx5k18=
  - secure: roRUWUyrq/0cCZlY0owAyHNUfC3/DoVoHvBrzGeG1Kki6YRseLLLm97koAOio9g5qD95LrzWaaYHzwrYt6mqasdvp5S2MMA7759TU3sD4xphs0BUllBQV0E9xxRULvyEOQ+El2aPPy3IEScaPfW2z7wAt5gXx3qq+NvbRMQ4WXE=
  - secure: IWbcpEya9zUD7ZmPUjTA8Ws9CqcJP0tsZEzpTDjYkrk5xNjDG0M+Z6CV/AKhh5GbsyT9IS1WWnABRj2x9qU3dO2JSY9OUCCYHLIbSfIlM97T4csD5PxZvQjT7k+JU10V9QHPiBnNW5XudUPNVCOhI9XWbpfJcPA8jqoTpdVpofA=
